# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

for r in range (1,6):
  for c in range(1,r+1):
    print((r+c+1)%2,end=' ')
  print()