# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

for i in range (1,6):
  for j in range(6,0,-1):
    print('*',end=' ')
  for k in range(1,i+1):
    print(k,end=' ')
  print()