# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

class student:

  def stuInput(student,name,rollno,fee):
    student.name=name
    student.rollno=rollno
    student.fee=fee

  def stuOutput(student):

    print("student name =",student.name)
    print("student rollno =",student.rollno)
    print("student fee =",student.fee)

obj=student()
obj.stuInput("Gagan",1,12.12)
obj.stuOutput()