# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqreZXjQpZAncdPlMUR14yh85AbTIE5e
"""

list_1=[10,20,10,30,10,20,30,10,50,70,90]  #initializing of a list
list_2=[]
for i in list_1:
   if list_1.count(i)>0:
    if i not in list_2:
       list_2.append(i)
print(list_2)