# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

class student:

  def stuInput(student): #REFERENCE
    student.name="Harleen"
    student.rollno=1
    student.fee=120.12

  def stuOutput(student): #REFERENCE

    print("student name =",student.name)
    print("student rollno =",student.rollno)
    print("student fee =",student.fee)

obj=student()
obj.stuInput()
obj.stuOutput()

