# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

a=int(input("Enter a number = "))
if(a%2==0):
    print("Number is even")
else:
    print("Number is odd")