filename=input("Enter First Name:")
f=open(filename,"a")
filecontent=input("Enter Your Line Contents:")
f.write(filecontent)
f.close()
f=open(filename,"r")
#print(f.readline())
for i in f:
    print(i)
f.close()
