# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

CGP=int(input("Enter CGP Value="))
if CGP==10:
  print("Excellent")
elif CGP==9:
  print("Very Good")
elif CGP==8:
  print("Good")
elif CGP==7:
  print("Average")
else:
  print("Work Hard")