# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

num1=input("Enter ist number =")
num2=input("Enter second number =")
num3=input("Enter third number =")
if(num1<num2 and num1<num3):
    print("Number 1 is Smallest Number")
elif(num2<num3 and num2<num1):
    print("Number 2 is Smallest Number")
elif(num3<num2 and num3<num1):
    print("Number 3 is Smallest Number")

num1=input("Enter ist number =")
num2=input("Enter second number =")
num3=input("Enter third number =")
if(num1<num2):
    print("Number 1 is smaller than Number 2")
    if(num1<num3):
     print("Number 1 is smaller than Number 3")
elif(num2<num3):
  print("Number 2 is smaller than Number 3")
if(num2<num1):
   print("Number 2 is smaller than Number 3")
elif(num3<num2):
   print("Number 3 is smaller than Number 2")
if(num3<num1):
   print("Number 3 is smaller than Number 1")