import sys
name=input("Enter your name")
rollno=input("Enter your rollno")
fee=input("Enter your fee")
gender=input("Enter your gender")
print("Student Name =",name)
print("Student Rollno =",rollno)
print("Student Fee =",fee)
print("Student Gender =",gender)
print(sys.getsizeof(name))
print(sys.getsizeof(rollno))
print(sys.getsizeof(fee))
print(sys.getsizeof(gender))
print(type(name))
print(type(rollno))
print(type(fee))
print(type(gender))