# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqreZXjQpZAncdPlMUR14yh85AbTIE5e
"""

S=[x**2 for x in range(10)]
V=[2**i for i in range(13)]
M=[x for x in S if x%2==0]
print(S)
print(V)
print(M)