# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqreZXjQpZAncdPlMUR14yh85AbTIE5e
"""

list1=[]
list1=[i for i in range (21) if i%2==0]
print(list1)