# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

num1 = int(input("Enter Number 1 = "))
num2 = int(input("Enter Number 2 = "))
num3 = int(input("Enter Number 3 = "))

if (num1<num2 and num1<num3):
    print("Number 1 is Smaller")
elif (num2<num3 and num2<num1):
    print("Number 2 is Smaller")
elif (num3<num1 and num3<num2):
    print("Number 3 is Smaller")