# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

num=int(input("Enter the number of which table you want ="))
print("Your number is =%d"%num)
for i in range (1,11):
  print("%d*%d=%d"%(num,i,num*i))