# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

def print_table(n,i):
    print(n,"*",i,"=",n*i)
    if i<10:
        return print_table(n,i+1)
n=int(input("Enter Number to get its Table:"))
print("Table of",n,"is:")
print_table(n,1)