# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

class student:

  def stuInput(self,name,rollno,fee):
    self.name=name
    self.rollno=rollno
    self.fee=fee

  def stuOutput(self):

    print("student name =",self.name)
    print("student rollno =",self.rollno)
    print("student fee =",self.fee)

obj=student()
obj.stuInput("Gagan",1,12.12)
obj.stuOutput()