# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4BJTBZV5ab-lQLtmcwDwoynD4q4cnz2
"""

class Kartik:
  pen='parker'

class Ansh:
  pencil='natraj'
  def use(self):
    K=Kartik()
    print("Pen Name =",K.pen)
    print("Pencil Name =",self.pencil)

A=Ansh()
A.use()

#Single Level Inheritance
class Kartik: #super class
  pen='parker'

class Ansh(Kartik): #ansh sub class
  pencil='natraj'
  def use(self):
    
    print("Pen Name =",self.pen)
    print("Pencil Name =",self.pencil)

A=Ansh()
A.use()