# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

import sys
name="kartik"
rollno=1
fee=120.120
gender='M'
print("Student Name =",name)
print("Student Rollno =",rollno)
print("Student Fee =",fee)
print("Student Gender =",gender)
print(sys.getsizeof(name))
print(sys.getsizeof(rollno))
print(sys.getsizeof(fee))
print(sys.getsizeof(gender))
print(type(name))
print(type(rollno))
print(type(fee))
print(type(gender))