# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

class student:

  def stuInput():
    student.name="Harleen"
    student.rollno=1
    student.fee=120.12

  def stuOutput():
    print("student name =",student.name)
    print("student rollno =",student.rollno)
    print("student fee =",student.fee)

student.stuInput()
student.stuOutput()