# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

import sys
class student:
  pass
objone=student
print(objone)
print(sys.getsizeof(objone)) #static class
objtwo=student()
print(objtwo)
print(sys.getsizeof(objtwo)) #dynamic class