# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnqAcB1kX_GcDcMOQd4W5JM40FidF89K
"""

str1="harleen"
print("my name is %s"%(str1))