# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13m1ba8Ilb22JecjNeggbjG5ln6biKiTy
"""

name="Kapil"
rollno=1
gender='F'
fee=120.120
print("Student Name =",name)
print("Student Rollno =",rollno)
print("Student Gender =",gender)
print("Student Fee =",fee)
print("Student Name =%s"%name)
print("Student Rollno =%d"%rollno)
print("Student Gender =%c"%gender)
print("Student Fee =%f"%fee)