# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqreZXjQpZAncdPlMUR14yh85AbTIE5e
"""

personal_details= {"name":"harleen","class":10,"rollno":1}
academic_details ={"mathsmarks":10,"physicsmarks":20,"chemistrymarks":80}
personal_details.update(academic_details)
print(personal_details)