# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4BJTBZV5ab-lQLtmcwDwoynD4q4cnz2
"""

class Kartik:
  pen='parker'

class Ansh:
  pencil='natraj'
  def use(self):
    K=Kartik()
    print("Pen Name =",K.pen)
    print("Pencil Name =",self.pencil)

A=Ansh()
A.use()

#Single Level Inheritance
class Kartik: #super class
  pen='parker'

class Ansh(Kartik): #ansh sub class
  pencil='natraj'
  def use(self):

    print("Pen Name =",self.pen)
    print("Pencil Name =",self.pencil)

A=Ansh()
A.use()

#MultiLevel Level Inheritance
class Kartik: #super class
  pen='parker'

class Ansh(Kartik): #ansh sub class acts as super class for Harleen
  pencil='natraj'
class Harleen(Ansh):
  eraser="Sensil"
class saini(Harleen):
  scale="apsara"

  def use(self):
    print("Pen Name =",self.pen)
    print("Pencil Name =",self.pencil)
    print("Eraser Name=",self.eraser)
    print("scale name=",self.scale)

S=saini()
S.use()

student={'name':'Raj','rollno':3,'english':50,'maths':60,'science':70,'punjabi':80,'hindi':90}
sum=0
for i in range(2,len(student)):
  value_at_index = list(student.values())[i]
  sum+=value_at_index
print("Total marks =",sum)
print("percentage =",sum//5)
student['total']=sum
student['percentage']=sum//5
print(student)

#METHOD OVERRIDING

class dost1:
  output("i am dost 1")

class dost2(dost1):
  output("i am dost 2")
  def use(self):
    print(self.output())
    print(self.output())

d2=dost2()
d2.output()

import platform as p
print(p.python_compiler())
print(p.platform())

try:
    a=int(input("Enter ist number ="))
    b=int(input("Enter second number ="))
    print(a/b)
except ZeroDivisionError:
    print("Donot divide a value by 0")

class MRException(Exception):
  def __init__(self,field):
    self.field=field
class MAException(Exception):
    def __init__(self,age):
     self.age=age
class MMException(Exception):
    def __init__(self,marks):
     self.marks=marks

try:
  name=(input("Enter your name ="))
  rollno=(input("Enter your rollno ="))
  age=(input("Enter your age ="))
  marks=(input("Enter your marks ="))
  if len(name)>0:
    if len(rollno)>0:
      if len(age)>0:
        if len(marks)>0:
          print("Name is entered")

  else:
    raise MRException("Field is empty")
except MRException as R:
    print(R)

try:
  name=(input("Enter your name ="))
  rollno=(input("Enter your rollno ="))
  age=(input("Enter your age ="))
  marks=(input("Enter your marks ="))
  if (int(age)>18 and int(age)<60):
     print("Entered age is valid")
  else:
      raise MAException("Entered age is not valid")
except MAException as A:
     print(A)

try:
  name=(input("Enter your name ="))
  rollno=(input("Enter your rollno ="))
  age=(input("Enter your age ="))
  marks=(input("Enter your marks ="))
  if (int(marks)>0 and int(marks)<100):
       print("Entered marks are valid")
  else:
       raise MMException("Entered marks are not valid")
except MMException as M:
     print(M)